//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandyProsServiceReports
{
    using System;
    using System.Collections.Generic;
    
    public partial class HandyProsRetailForm
    {
        public int Id { get; set; }
        public string CustomerName { get; set; }
        public string Reference { get; set; }
        public string SheetNumber { get; set; }
        public string HandyProName { get; set; }
        public System.DateTime DateofInspection { get; set; }
        public System.TimeSpan TimeOfInspection { get; set; }
        public string ElectricalInspectionDetails { get; set; }
        public Nullable<bool> IsTrackLightsCheck { get; set; }
        public string TrackLightsStatus { get; set; }
        public Nullable<bool> IsLedT8T5Check { get; set; }
        public string LedT8T5Status { get; set; }
        public Nullable<bool> IsDownLightsCheck { get; set; }
        public string DownLightsStatus { get; set; }
        public Nullable<bool> IsSpotsCheck { get; set; }
        public string SpotsStatus { get; set; }
        public Nullable<bool> IsDBoardCheck { get; set; }
        public string DBoardStatus { get; set; }
        public Nullable<bool> IsEmergencyCheck { get; set; }
        public string EmergencyStatus { get; set; }
        public Nullable<bool> IsPlugsCheck { get; set; }
        public string PlugsStatus { get; set; }
        public Nullable<bool> IsExitLightsCheck { get; set; }
        public string ExitLightsStatus { get; set; }
        public Nullable<bool> IsSignageCheck { get; set; }
        public string SignageStatus { get; set; }
        public Nullable<bool> IsCamerasCheck { get; set; }
        public string CamerasStatus { get; set; }
        public Nullable<bool> IsUPSCheck { get; set; }
        public string UPSStatus { get; set; }
        public string MechanicalInspectionDetails { get; set; }
        public Nullable<bool> IsVRVVRFCheck { get; set; }
        public string VRVVRFStatus { get; set; }
        public Nullable<bool> IsAHUCheck { get; set; }
        public string AHUStatus { get; set; }
        public Nullable<bool> IsDuctSupplyCheck { get; set; }
        public string DuctSupplyStatus { get; set; }
        public Nullable<bool> IsGrillCheck { get; set; }
        public string GrillStatus { get; set; }
        public Nullable<bool> IsSplitsCheck { get; set; }
        public string SplitsStatus { get; set; }
        public Nullable<bool> IsFiltersCheck { get; set; }
        public string FiltersStatus { get; set; }
        public Nullable<bool> IsDrainCheck { get; set; }
        public string DrainStatus { get; set; }
        public Nullable<bool> IsFreshAirCheck { get; set; }
        public string FreshAirStatus { get; set; }
        public Nullable<bool> IsExhaustCheck { get; set; }
        public string ExhaustStatus { get; set; }
        public Nullable<bool> IsFloorDrainCheck { get; set; }
        public string FloorDrainStatus { get; set; }
        public Nullable<bool> IsManholeCheck { get; set; }
        public string ManholeStatus { get; set; }
        public string CivilInspectionDetails { get; set; }
        public Nullable<bool> IsFurnitureCheck { get; set; }
        public string FurnitureStatus { get; set; }
        public Nullable<bool> IsDrawersCheck { get; set; }
        public string DrawersStatus { get; set; }
        public Nullable<bool> IsDoorknobsCheck { get; set; }
        public string DoorknobsStatus { get; set; }
        public Nullable<bool> IsHingesCheck { get; set; }
        public string HingesStatus { get; set; }
        public Nullable<bool> IsMirrorsCheck { get; set; }
        public string MirrorsStatus { get; set; }
        public Nullable<bool> IsShelvesCheck { get; set; }
        public string ShelvesStatus { get; set; }
        public Nullable<bool> IsRacksCheck { get; set; }
        public string RacksStatus { get; set; }
        public Nullable<bool> IsWindowsCheck { get; set; }
        public string WindowsStatus { get; set; }
        public Nullable<bool> IsCeilingCheck { get; set; }
        public string CeilingStatus { get; set; }
        public Nullable<bool> IsFloorCheck { get; set; }
        public string FloorStatus { get; set; }
        public Nullable<bool> IsFridgeCheck { get; set; }
        public string FridgeStatus { get; set; }
        public string HandyProsTechnicianSignature { get; set; }
        public string CustomerRepresentativeSignature { get; set; }
    }
}
